=== libersky/schoolProjects/xml Katalog hotelů/hotelySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"  
    targetNamespace="urn:vse.cz:hotely"
    xmlns="urn:vse.cz:hotely"
    xmlns:vysledky="urn:vse.cz:hotely" 
    xmlns:h="urn:vse.cz:hotely"
> 

    <xs:element name="hotely" type="hotelType">
        <xs:key name="keyNazev">
            <xs:selector xpath="h:budova/h:nazev"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:keyref refer="keyNazev" name="keyRefEmail">
            <xs:selector xpath="h:budova/h:kontakt"></xs:selector>
            <xs:field xpath="@vlastnik"></xs:field>
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="hotelType">
        <xs:sequence>
            <xs:element name="budova" type="budovaType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="budovaType">
        <xs:sequence>
            <xs:element name="nazev" type="xs:string"/>
            <xs:element name="hvezdy" type="hvezdyType"/>
            <xs:element name="kontakt" type="kontaktType"/>
            <xs:element name="predstavenstvo" type="predstavenstvoType"/>
            <xs:element name="pocetDostupnychPokoju" type="pocetDostupnychPokojuType"/>
            <xs:element name="pokoje" type="pokojeType"/>
            <xs:element name="vybaveniHotelu" type="vybaveniType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="hvezdyType">
        <xs:restriction base="xs:int">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="kontaktType">
        <xs:sequence>
            <xs:element name="telefon" type="telefonType"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="adresa" type="adresaType"/>
        </xs:sequence>
        <xs:attribute name="vlastnik" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="adresaType">
        <xs:sequence>
            <xs:element name="ulice" type="xs:string"/>
            <xs:element name="cp" type="xs:int"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="psc" type="pscType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="pscType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}\s?\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="predstavenstvoType">
        <xs:sequence>
            <xs:element name="osoba" type="osobaType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="osobaType">
        <xs:sequence>
            <xs:element name="jmeno" type="xs:string"/>
            <xs:element name="kontakt" type="osobniKontaktType"/>
        </xs:sequence>
        <xs:attribute name="pozice" type="poziceType" use="required"/>
    </xs:complexType>

    <xs:complexType name="osobniKontaktType">
        <xs:sequence>
            <xs:element name="telefon" type="telefonType"/>
            <xs:element name="email" type="emailType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="poziceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Majitel"/>
            <xs:enumeration value="Vedoucí"/>
            <xs:enumeration value="Zástupce"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*@.*\..*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="telefonType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+\d{3}\s?\d{3}\s?\d{3}\s?\d{3}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="pocetDostupnychPokojuType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="pokojeType">
        <xs:sequence>
            <xs:element name="pokoj" type="pokojType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="pokojType">
        <xs:sequence>
            <xs:element name="pocetLuzek" type="xs:int"/>
            <xs:element name="typ" type="xs:string"/>
            <xs:element name="socialniZarizeni" type="socialniZarizeniType"/>
            <xs:element name="vybaveniPokoje" type="vybaveniType"/>
            <xs:element name="cenaZaNoc" type="cenaType"/>
        </xs:sequence>
        <xs:attribute name="provoz" type="provozType" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="socialniZarizeniType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ano"/>
            <xs:enumeration value="Ne"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="vybaveniType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(.*,)*(.*)"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cenaType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="provozType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ano"/>
            <xs:enumeration value="Ne"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== libersky/schoolProjects/xml Katalog hotelů/hotely.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="hotelySchematron.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/css" href="hotelyCSS.css"?>
<hotely xmlns="urn:vse.cz:hotely"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:vse.cz:hotely hotelySchema.xsd">
    <budova>
        <nazev>Jezerka</nazev>
        <hvezdy>3</hvezdy>
        <kontakt vlastnik="Šumava">
            <telefon>+420741258639</telefon>
            <email>jezerka@hotely.cz</email>
            <adresa>
                <ulice>Pod Skalkou</ulice>
                <cp>22</cp>
                <mesto>Albrechtice v Jizerských horách</mesto>
                <psc>468 43</psc>
            </adresa>
        </kontakt>
        <predstavenstvo>
            <osoba pozice="Majitel">
                <jmeno>Franta Omáčka</jmeno>
                <kontakt>
                    <telefon>+420896754321</telefon>
                    <email>franta.omacka@hotely.cz</email>
                </kontakt>
            </osoba>
            <osoba pozice="Vedoucí">
                <jmeno>Josef Novák</jmeno>
                <kontakt>
                    <telefon>+420326951874</telefon>
                    <email>josef.novak@hotely.cz</email>
                </kontakt>
            </osoba>
            <osoba pozice="Zástupce">
                <jmeno>Marie Hajzerová</jmeno>
                <kontakt>
                    <telefon>+420456823971</telefon>
                    <email>marie.hajzerova@hotely.cz</email>
                </kontakt>
            </osoba>
        </predstavenstvo>
        <pocetDostupnychPokoju>1</pocetDostupnychPokoju>
        <pokoje>
            <pokoj provoz="Ne">
                <pocetLuzek>4</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednička, televize, kuchyňka</vybaveniPokoje>
                <cenaZaNoc>2000</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ne">
                <pocetLuzek>2</pocetLuzek>
                <typ>2kk</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednička, televize</vybaveniPokoje>
                <cenaZaNoc>1200</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>2</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednicka, televize, kuchyňka, vinotéka</vybaveniPokoje>
                <cenaZaNoc>1500</cenaZaNoc>
            </pokoj>
        </pokoje>
        <vybaveniHotelu>jídelna, klubovna, bar</vybaveniHotelu>
    </budova>
    
    <budova>
        <nazev>Šumava</nazev>
        <hvezdy>4</hvezdy>
        <kontakt vlastnik="Šumava">
            <telefon>+420741258879</telefon>
            <email>sumava@hotely.cz</email>
            <adresa>
                <ulice>Svatoplukova</ulice>
                <cp>71</cp>
                <mesto>Žleby</mesto>
                <psc>789 43</psc>
            </adresa>
        </kontakt>
        <predstavenstvo>
            <osoba pozice="Majitel">
                <jmeno>Filip Tříska</jmeno>
                <kontakt>
                    <telefon>+420526754321</telefon>
                    <email>filip.triska@hotely.cz</email>
                </kontakt>
            </osoba>
            <osoba pozice="Vedoucí">
                <jmeno>Petr Truhlar</jmeno>
                <kontakt>
                    <telefon>+420326888874</telefon>
                    <email>filip.truhlar@hotely.cz</email>
                </kontakt>
            </osoba>
            <osoba pozice="Zástupce">
                <jmeno>Marian Hajzer</jmeno>
                <kontakt>
                    <telefon>+420486823971</telefon>
                    <email>marian.hajzer@hotely.cz</email>
                </kontakt>
            </osoba>
        </predstavenstvo>
        <pocetDostupnychPokoju>3</pocetDostupnychPokoju>
        <pokoje>
            <pokoj provoz="Ano">
                <pocetLuzek>5</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednička, televize, kuchyňka</vybaveniPokoje>
                <cenaZaNoc>5000</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>2</pocetLuzek>
                <typ>2kk</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednička, televize, fen</vybaveniPokoje>
                <cenaZaNoc>1600</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ne">
                <pocetLuzek>2</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ne</socialniZarizeni>
                <vybaveniPokoje>lednicka, televize</vybaveniPokoje>
                <cenaZaNoc>800</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>3</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednicka, televize, kuchyňka</vybaveniPokoje>
                <cenaZaNoc>1700</cenaZaNoc>
            </pokoj>
        </pokoje>
        <vybaveniHotelu>jídelna, klubovna, bar, atrium</vybaveniHotelu>
    </budova>
    
    <budova>
        <nazev>Leonora</nazev>
        <hvezdy>2</hvezdy>
        <kontakt vlastnik="Leonora">
            <telefon>+420 777 258 649</telefon>
            <email>leonora@hotely.cz</email>
            <adresa>
                <ulice>Na Příkopech</ulice>
                <cp>5</cp>
                <mesto>Veveřice</mesto>
                <psc>468 88</psc>
            </adresa>
        </kontakt>
        <predstavenstvo>
            <osoba pozice="Majitel">
                <jmeno>Josef Kratochvíl</jmeno>
                <kontakt>
                    <telefon>+420892344328</telefon>
                    <email>josef.kratochvil@hotely.cz</email>
                </kontakt>
            </osoba>
            <osoba pozice="Vedoucí">
                <jmeno>Milan Rubes</jmeno>
                <kontakt>
                    <telefon>+420876951874</telefon>
                    <email>milan.rubes@hotely.cz</email>
                </kontakt>
            </osoba>
            <osoba pozice="Zástupce">
                <jmeno>Monika Nekonecna</jmeno>
                <kontakt>
                    <telefon>+420456553971</telefon>
                    <email>monika.nekonecna@hotely.cz</email>
                </kontakt>
            </osoba>
        </predstavenstvo>
        <pocetDostupnychPokoju>5</pocetDostupnychPokoju>
        <pokoje>
            <pokoj provoz="Ano">
                <pocetLuzek>4</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednička, televize, kuchyňka</vybaveniPokoje>
                <cenaZaNoc>2000</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>2</pocetLuzek>
                <typ>2kk</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednička, televize</vybaveniPokoje>
                <cenaZaNoc>1200</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>2</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednicka, televize, kuchyňka, vinotéka</vybaveniPokoje>
                <cenaZaNoc>1500</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>2</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednicka, televize, kuchyňka, vinotéka</vybaveniPokoje>
                <cenaZaNoc>1500</cenaZaNoc>
            </pokoj>
            <pokoj provoz="Ano">
                <pocetLuzek>2</pocetLuzek>
                <typ>2+1</typ>
                <socialniZarizeni>Ano</socialniZarizeni>
                <vybaveniPokoje>lednicka, televize, kuchyňka, vinotéka</vybaveniPokoje>
                <cenaZaNoc>1500</cenaZaNoc>
            </pokoj>
        </pokoje>
        <vybaveniHotelu>jídelna, klubovna, bar</vybaveniHotelu>
    </budova>
    
</hotely>
